"""add admin and banned flags to user

Revision ID: 654471fbb152
Revises: 96a0fe963c55
Create Date: 2025-12-08 13:57:06.343128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654471fbb152'
down_revision = '96a0fe963c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
